/**
 * Build-time only: Shiki via fumadocs-core must not ship in the Workers bundle
 * (`import("shiki")` pulls ~10MB of language grammars).
 *
 * Run: `bun run highlight:packaging` (also wired into build / deploy / preview).
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { getHighlighter } from "fumadocs-core/highlight";
import { PACKAGING_EXAMPLES } from "../lib/packaging-examples";

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(here, "../lib/packaging-examples.highlighted.ts");

const SHIKI_LANG = {
  typescript: "typescript",
  javascript: "javascript",
} as const;

async function main(): Promise<void> {
  const highlighter = await getHighlighter("js", {
    langs: ["typescript", "javascript"],
    themes: ["github-light", "github-dark"],
  });

  const examples = PACKAGING_EXAMPLES.map((ex) => {
    const lang = SHIKI_LANG[ex.id];
    const options = {
      lang,
      themes: {
        light: "github-light" as const,
        dark: "github-dark" as const,
      },
      defaultColor: false as const,
    };
    return {
      id: ex.id,
      label: ex.label,
      why: ex.why,
      badHtml: highlighter.codeToHtml(ex.bad, options),
      goodHtml: highlighter.codeToHtml(ex.good, options),
    };
  });

  const body = `/* AUTO-GENERATED by scripts/generate-packaging-highlights.ts — do not edit. */
import type { PackagingLangId } from "@/lib/packaging-examples";

export type HighlightedPackagingExample = {
  id: PackagingLangId;
  label: string;
  why: string;
  badHtml: string;
  goodHtml: string;
};

export const HIGHLIGHTED_PACKAGING_EXAMPLES: HighlightedPackagingExample[] =
  ${JSON.stringify(examples, null, 2)};
`;

  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, body, "utf8");
  console.log(`Wrote ${examples.length} highlighted examples → ${outPath}`);
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
